# Generated by Django 5.1.5 on 2025-05-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100)),
                ('listy', models.TextField()),
                ('plody', models.TextField()),
                ('kura', models.TextField()),
                ('tvar_koruny', models.TextField()),
                ('drevo', models.TextField()),
                ('rozpoznavaci_znaky', models.TextField()),
            ],
        ),
    ]
