# Generated by Django 5.1.5 on 2025-05-04 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stromy_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StromObrazek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obrazek', models.ImageField(upload_to='stromy_obrazky/')),
                ('strom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obrazky', to='stromy_app.strom')),
            ],
        ),
    ]
